export const currCode = [
  'AED',
  'AFN',
  'ALL',
  'AMD',
  'ANG',
  'AOA',
  'ARS',
  'AUD',
  'AWG',
  'AZN',
  'BAM',
  'BBD',
  'BDT',
  'BGN',
  'BHD',
  'BIF',
  'BMD',
  'BND',
  'BOB',
  'BOV',
  'BRL',
  'BSD',
  'BTN',
  'BWP',
  'BYN',
  'BZD',
  'CAD',
  'CDF',
  'CHF',
  'CLF',
  'CLP',
  'CNY',
  'COP',
  'CRC',
  'CUC',
  'CUP',
  'CVE',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ERN',
  'ETB',
  'EUR',
  'FJD',
  'FKP',
  'GBP',
  'GEL',
  'GHS',
  'GIP',
  'GMD',
  'GNF',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HRK',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'IQD',
  'IRR',
  'ISK',
  'JMD',
  'JOD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KMF',
  'KPW',
  'KRW',
  'KWD',
  'KYD',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'LTL',
  'LVL',
  'LYD',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MRO',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'OMR',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PYG',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SAR',
  'SBD',
  'SCR',
  'SDG',
  'SEK',
  'SGD',
  'SHP',
  'SLL',
  'SOS',
  'SRD',
  'SSP',
  'STD',
  'SVC',
  'SYP',
  'SZL',
  'THB',
  'TJS',
  'TMT',
  'TND',
  'TOP',
  'TRY',
  'TTD',
  'TWD',
  'TZS',
  'UAH',
  'UGX',
  'USD',
  'UYU',
  'UZS',
  'VEF',
  'VND',
  'VUV',
  'WST',
  'XAF',
  'XCD',
  'XOF',
  'XPF',
  'YER',
  'ZAR',
  'ZMW',
  'ZWL'
]

// const currCode = [
//   'AED - UAE Dirham',
//   'AFN - Afghan Afghani',
//   'ALL - Albanian Lek',
//   'AMD - Armenian Dram',
//   'ANG - Netherlands Antillean Guilder',
//   'AOA - Angolan Kwanza',
//   'ARS - Argentine Peso',
//   'AUD - Australian Dollar',
//   'AWG - Aruban Florin',
//   'AZN - Azerbaijanian Manat',
//   'BAM - Convertible Mark',
//   'BBD - Barbados Dollar',
//   'BDT - Bangladeshi Taka',
//   'BGN - Bulgarian Lev',
//   'BHD - Bahraini Dinar',
//   'BIF - Burundi Franc',
//   'BMD - Bermudian Dollar',
//   'BND - Brunei Dollar',
//   'BOB - Bolivian Boliviano',
//   'BOV - Bolivian Mvdol',
//   'BRL - Brazilian Real',
//   'BSD - Bahamian Dollar',
//   'BTN - Bhutanese Ngultrum',
//   'BWP - Botswanan Pula',
//   'BYN - Belarussian Ruble',
//   'BZD - Belize Dollar',
//   'CAD - Canadian Dollar',
//   'CDF - Congolese Franc',
//   'CHF - Swiss Franc',
//   'CLF - Unidades de fomento',
//   'CLP - Chilean Peso',
//   'CNY - Yuan Renminbi',
//   'COP - Colombian Peso',
//   'CRC - Costa Rican Colon',
//   'CUC - Peso Convertible',
//   'CUP - Cuban Peso',
//   'CVE - Cape Verde Escudo',
//   'CZK - Czech Koruna',
//   'DJF - Djibouti Franc',
//   'DKK - Danish Krone',
//   'DOP - Dominican Peso',
//   'DZD - Algerian Dinar',
//   'EGP - Egyptian Pound',
//   'ERN - Eritrean Nakfa',
//   'ETB - Ethiopian Birr',
//   'EUR - European Union Euro',
//   'FJD - Fiji Dollar',
//   'FKP - Falkland Islands Pound',
//   'GBP - Great British Pound Sterling',
//   'GEL - Georgian Lari',
//   'GHS - Ghanaian Cedi',
//   'GIP - Gibraltar Pound',
//   'GMD - Gambian Dalasi',
//   'GNF - Guinea Franc',
//   'GTQ - Guatemalan Quetzal',
//   'GYD - Guyana Dollar',
//   'HKD - Hong Kong Dollar',
//   'HNL - Honduran Lempira',
//   'HRK - Croatian Kuna',
//   'HTG - Haitian Gourde',
//   'HUF - Hungarian Forint',
//   'IDR - Indonesian Rupiah',
//   'ILS - New Israeli Sheqel',
//   'INR - Indian Rupee',
//   'IQD - Iraqi Dinar',
//   'IRR - Iranian Rial',
//   'ISK - Iceland Krona',
//   'JMD - Jamaican Dollar',
//   'JOD - Jordanian Dinar',
//   'JPY - Japanese Yen',
//   'KES - Kenyan Shilling',
//   'KGS - Kyrgyzstani Som',
//   'KHR - Cambodian Riel',
//   'KMF - Comoro Franc',
//   'KPW - North Korean Won',
//   'KRW - South Korean Won',
//   'KWD - Kuwaiti Dinar',
//   'KYD - Cayman Islands Dollar',
//   'KZT - Kazakhstani Tenge',
//   'LAK - Laotian Kip',
//   'LBP - Lebanese Pound',
//   'LKR - Sri Lanka Rupee',
//   'LRD - Liberian Dollar',
//   'LSL - Lesotho Loti',
//   'LTL - Lithuanian Litas',
//   'LVL - Latvian Lats',
//   'LYD - Libyan Dinar',
//   'MAD - Moroccan Dirham',
//   'MDL - Moldovan Leu',
//   'MGA - Malagasy Ariary',
//   'MKD - Macedonian Denar',
//   'MMK - Myanmar Kyat',
//   'MNT - Mongolian Tugrik',
//   'MOP - Macanese Pataca',
//   'MRO - Mauritanian Ouguiya',
//   'MUR - Mauritius Rupee',
//   'MVR - Maldivian Rufiyaa',
//   'MWK - Malawian Kwacha',
//   'MXN - Mexican Peso',
//   'MYR - Malaysian Ringgit',
//   'MZN - Mozambique Metical',
//   'NAD - Namibia Dollar',
//   'NGN - Nigerian Naira',
//   'NIO - Cordoba Oro',
//   'NOK - Norwegian Krone',
//   'NPR - Nepalese Rupee',
//   'NZD - New Zealand Dollar',
//   'OMR - Rial Omani',
//   'PAB - Panamanian Balboa',
//   'PEN - Peruvian Sol',
//   'PGK - Papua New Guinean Kina',
//   'PHP - Philippine Peso',
//   'PKR - Pakistan Rupee',
//   'PLN - Polish Zloty',
//   'PYG - Paraguayan Guarani',
//   'QAR - Qatari Rial',
//   'RON - New Romanian Leu',
//   'RSD - Serbian Dinar',
//   'RUB - Russian Ruble',
//   'RWF - Rwanda Franc',
//   'SAR - Saudi Riyal',
//   'SBD - Solomon Islands Dollar',
//   'SCR - Seychelles Rupee',
//   'SDG - Sudanese Pound',
//   'SEK - Swedish Krona',
//   'SGD - Singapore Dollar',
//   'SHP - Saint Helena Pound',
//   'SLL - Sierra Leonean Leone',
//   'SOS - Somali Shilling',
//   'SRD - Surinam Dollar',
//   'SSP - South Sudanese Pound',
//   'STD - São Tomé and Príncipe Dobra',
//   'SVC - El Salvador Colon',
//   'SYP - Syrian Pound',
//   'SZL - Swazi Lilangeni',
//   'THB - Thai Baht',
//   'TJS - Tajikistani Somoni',
//   'TMT - Turkmenistan New Manat',
//   'TND - Tunisian Dinar',
//   'TOP - Tongan Pa’anga',
//   'TRY - Turkish Lira',
//   'TTD - Trinidad and Tobago Dollar',
//   'TWD - New Taiwan Dollar',
//   'TZS - Tanzanian Shilling',
//   'UAH - Ukrainian Hryvnia',
//   'UGX - Uganda Shilling',
//   'USD - US Dollar',
//   'UYU - Peso Uruguayo',
//   'UZS - Uzbekistan Sum',
//   'VEF - Venezuelan Bolivar',
//   'VND - Vietnamese Dong',
//   'VUV - Vanuatu Vatu',
//   'WST - Samoan Tala',
//   'XAF - CFA Franc BEAC',
//   'XCD - East Caribbean Dollar',
//   'XOF - CFA Franc BCEAO',
//   'XPF - CFP Franc',
//   'YER - Yemeni Rial',
//   'ZAR - South African Rand',
//   'ZMW - Zambian Kwacha',
//   'ZWL - Zimbabwe Dollar'
// ]